server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spms?allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: asdfew12345
  mvc:
    view:
      suffix: .html
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
#应用配置
application:
  loginUrl: "http://localhost:3000/login"