spring:
  jpa:
    show-sql: true
    hibernate:
      # 生产模式请严格使用 validate
      ddl-auto: update
  datasource:
    url: "jdbc:mysql://localhost:3306/spms?allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false"
    username: "your_database_username"
    password: "your_database_password"
  data:
    redis:
      host: "your_redis_host_default_localhost"
      port: 6379
      database: 0
      password: "your_redis_password"
  mail:
    host: "smtp.exmail.qq.com"
    port: 465
    username: "your_email@your_domain.com"
    password: "your_email_password"
airpower:
  mqtt:
    host: "your_mqtt_host_default_127.0.0.1"
    port: 1883
    user: "your_mqtt_username"
    pass: "your_mqtt_password"
app:
  influxdb:
    url: "your_influxdb_url"
    token: "your_influxdb_token"
    org: "your_influxdb_org"
    bucket: "your_influxdb_bucket"
