server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spms?allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: asdfew12345
  mvc:
    view:
      suffix: .html
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  mqtt:
    host: md4.cn
    port: 1883
    user: mqttroot
    pass: asdfew12345
  influxdb:
    url: http://md4.cn:8086
    token: spms
    org: spms
    bucket: spms
#应用配置
application:
  loginUrl: "http://localhost:3000/login"